apiVersion: apps/v1beta1 
kind: Deployment 
metadata: 
  name: journal-api-deployment 
  labels: 
    name: journal-api 
spec: 
  replicas: 2 
  template: 
    metadata: 
      labels: 
        name: journal-api 
    spec: 
      containers: 
      - image: gcr.io/poetic-now-331405/journal-api:v1 
        name: journal-api 
        ports: 
        - name: http-server 
  containerPort: 5000 