apiVersion: v1 
kind: Service 
metadata: 
 name: journal-api 
 labels: 
   name: journal-api 
spec: 
 type: LoadBalancer 
 ports: 
   - port: 5000 
     targetPort: http-server 
     protocol: TCP 
 selector: 
name: journal-api 

