apiVersion: v1
kind: Service
metadata:
  name: journal-api-service
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: http-port
  selector:
    app: journal-api
    tier: backend
  type: LoadBalancer