apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: journal-api 
  labels: 
    name: journal-api 
spec: 
  replicas: 2 
  selector:
    matchLabels:
      app: journal-api 
  template: 
    metadata: 
      labels: 
        app: journal-api 
    spec:
      containers:
      - name: journal-api 
        image: gcr.io/poetic-now-331405/journal-api@sha256:f5cae0bf86825015762c99344894a2e28bc8ed8010793bce7341f313a9d36b35 
        ports:
        - containerPort: 8080