apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: journal-api 
  labels: 
    name: journal-api 
spec: 
  replicas: 1 
  selector:
    matchLabels:
      app: journal-api 
  template: 
    metadata: 
      labels: 
        app: journal-api 
    spec:
      containers:
      - name: journal-api 
        image: gcr.io/poetic-now-331405/journal-api:v2 
        ports:
        - containerPort: 5000